<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;

/**
 * This is the base-model class for table "galeri".
 *
 * @property integer $id
 * @property integer $nama
 * @property integer $harga
 * @property integer $ha
 * @property string $aliasModel
 */
abstract class Galeri extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'galeri';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nama', 'harga', 'ha'], 'required'],
            [['nama', 'harga', 'ha'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama' => 'Nama',
            'harga' => 'Harga',
            'ha' => 'Ha',
        ];
    }




}
