<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "menu".
 *
 * @property integer $id
 * @property string $menu
 * @property string $icon
 * @property string $parent
 * @property string $module
 * @property string $controller
 * @property string $aliasModel
 */
abstract class Menu extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'menu';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['menu', 'icon'], 'required'],
            [['menu', 'icon', 'parent', 'module', 'controller'], 'string', 'max' => 100]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'menu' => 'Menu',
            'icon' => 'Icon',
            'parent' => 'Parent',
            'module' => 'Module',
            'controller' => 'Controller',
        ];
    }


    public function getMenu(){
        return $this->hasMany(Menu::className(), ['id' => 'id']);
    }


}
