<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "post".
 *
 * @property integer $id
 * @property string $judul
 * @property string $isi
 * @property string $tanggal
 * @property string $gambar
 * @property string $aliasModel
 */
abstract class Post extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'post';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['judul', 'isi', 'tanggal', 'gambar'], 'required'],
            [['isi'], 'string'],
            [['tanggal'], 'safe'],
            [['judul', 'gambar'], 'string', 'max' => 100]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'judul' => 'Judul',
            'isi' => 'Isi',
            'tanggal' => 'Tanggal',
            'gambar' => 'Gambar',
        ];
    }




}
