<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "role_menu".
 *
 * @property integer $id
 * @property integer $role
 * @property integer $menu
 * @property string $aliasModel
 */
abstract class RoleMenu extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'role_menu';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['role', 'menu'], 'required'],
            [['role', 'menu'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'role' => 'Role',
            'menu' => 'Menu',
        ];
    }




}
